<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5171" started-at="2020-06-17T15:47:25 IST" finished-at="2020-06-17T15:47:30 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5171" started-at="2020-06-17T15:47:25 IST" finished-at="2020-06-17T15:47:30 IST">
      <class name="testing.TestScript">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testing.TestScript@5c5a1b69]" name="beforeTest" is-config="true" duration-ms="3892" started-at="2020-06-17T15:47:25 IST" finished-at="2020-06-17T15:47:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="titlecheck()[pri:0, instance:testing.TestScript@5c5a1b69]" name="titlecheck" duration-ms="150" started-at="2020-06-17T15:47:29 IST" finished-at="2020-06-17T15:47:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titlecheck -->
        <test-method status="PASS" signature="adminLogin()[pri:1, instance:testing.TestScript@5c5a1b69]" name="adminLogin" duration-ms="364" started-at="2020-06-17T15:47:29 IST" finished-at="2020-06-17T15:47:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adminLogin -->
        <test-method status="FAIL" signature="postchanges()[pri:2, instance:testing.TestScript@5c5a1b69]" name="postchanges" duration-ms="99" started-at="2020-06-17T15:47:30 IST" finished-at="2020-06-17T15:47:30 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to Online Book Store] but found [Online Book Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to Online Book Store] but found [Online Book Store]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testing.TestScript.postchanges(TestScript.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postchanges -->
        <test-method status="PASS" signature="prechanges()[pri:2, instance:testing.TestScript@5c5a1b69]" name="prechanges" duration-ms="66" started-at="2020-06-17T15:47:30 IST" finished-at="2020-06-17T15:47:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prechanges -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testing.TestScript@5c5a1b69]" name="afterTest" is-config="true" duration-ms="540" started-at="2020-06-17T15:47:30 IST" finished-at="2020-06-17T15:47:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testing.TestScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
